# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - if [ $TRAVIS_OS_NAME = linux ]; then devel; fi
os:
  - linux
  - osx

sudo: false
cache: packages
